### ISSUE TITLE
Table headers are messed up

### ISSUE THREAD

**Issue by pguardiario** [xylish7/nextui-theme-generator#2]
This is great but I can't use it because the dark mode table headers are styled wrong

**Comment by xylish7** [comment]
Will look into it. Thanks for mentioning it. Can you also provide a screenshot and some more details just to make sure we are on the same page?

**Comment by pguardiario** [comment]
Oh sorry, I already removed the styles but if it helps I remember the weird
style was in default 100

**Comment by xylish7** [comment]
I've added the table component to the showcase, but I'm unable to see an issue with the table headers. Can you provide me an example? You can also check it live since I deployed it to production.

![image](https://github.com/user-attachments/assets/06f579c4-53fb-404e-8644-1853a8583c78)

**Comment by pguardiario** [comment]
Yes it looks ok now, If you didn't change anything it might be my issue
because I've been having nextui style issues in development. Sorry about
that.

**Comment by xylish7** [comment]
No problem! Will close this issue for now 👍🏻
